### ISSUE TITLE
TXID bytes need to be passed in reverse byte order.

### ISSUE THREAD

**Issue by CRex15** [lightninglabs/lightning-api-ng#14]
The description for TXID in [Label Transaction](https://lightning.engineering/api-docs/api/lnd/wallet-kit/label-transaction) should include a note that, in the case of GRPC, the TXID needs to be passed in reverse byte order. More info here in the section [Searching for TXIDs in the blockchain](https://learnmeabitcoin.com/technical/txid)

**Comment by jamaljsr** [comment]
Thanks for the suggestion. This change would need to be made in the `lnd` repo's [walletkit.proto](https://github.com/lightningnetwork/lnd/blob/d44823f6e8580d2fa5f193a5382be351610f7c2b/lnrpc/walletrpc/walletkit.proto#L985) file since all of our docs are generated from the protos. Would you like to submit a PR to update it there? If not, we can take care of it.

**Comment by CRex15** [comment]
Let me try to do it, yeah!

**Comment by jamaljsr** [comment]
Cool. Thanks for pointing that out.

Going to close this issue since there are no changes needed in this repo.
