### ISSUE TITLE
get rid of unnecessary index.html at the end of API docs URLs

### ISSUE THREAD

**Issue by ZZiigguurraatt** [lightninglabs/lightning-api-ng#32]
Please get rid of unnecessary index.html at the end of URLs. For some reason, if reloading an API doc page, it will redirect to a link with an index.html tacked onto the end. This clutters the URL and provides no added value.

For example, if I go to

https://lightning.engineering/api-docs/category/rfq-service

it will redirect to

https://lightning.engineering/api-docs/category/rfq-service/index.html

.

As another example,

https://lightning.engineering/api-docs/api/taproot-assets/rfq/add-asset-buy-offer

redirects to

https://lightning.engineering/api-docs/api/taproot-assets/rfq/add-asset-buy-offer/index.html

.

This redirection happens usually, but not always when first going to a page. Reloading the page causes it to happen more frequently than not.

**Comment by jamaljsr** [comment]
This redirect is triggered by the gcloud host. If the url doesn't contain a trailing slash, it will redirect to  `/index.html`. While we cannot change this behavior on gcloud, what we can do is configure the site to always append a trailing slash for all links. With this implemented, visitors will get a proper url with the trailing slash if they copy the url from the address bar or by right-clicking on a link. 

Note: this wouldn't change the behavior of the redirect described above. it would simply make it less likely that anyone would obtain a url without a trailing slash because all of the site links will have it in them. If you manually remove the slash at the end of any url, the redirect would still occur.

**Comment by ZZiigguurraatt** [comment]
> This redirect is triggered by the gcloud host. If the url doesn't contain a trailing slash, it will redirect to `/index.html`. While we cannot change this behavior on gcloud, what we can do is configure the site to always append a trailing slash for all links. With this implemented, visitors will get a proper url with the trailing slash if they copy the url from the address bar or by right-clicking on a link.
> 
> Note: this wouldn't change the behavior of the redirect described above. it would simply make it less likely that anyone would obtain a url without a trailing slash because all of the site links will have it in them. If you manually remove the slash at the end of any url, the redirect would still occur.

So far, this fix has been working good enough for me. I haven't hit the case without the trailing slash.
